# Generated by Django 4.2.6 on 2024-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='credit',
            field=models.FloatField(null=True, verbose_name='课程学分'),
        ),
    ]
